name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/GitHub/color-my-toys
          git pull origin develop &&
          docker rm color-my-toys-front-end-container || true
          docker rmi color-my-toys-front-end-image || true
          docker build --no-cache -t color-my-toys-front-end-image .
          docker run -d -p 5050:80 --name color-my-toys-front-end-container color-my-toys-front-end-image 
